# .github/workflows/CICD.yml
name:
  Tests
on: 
  push:

jobs:
  Windows:
    name: Validate API spec
    runs-on: windows-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v1
      - uses: kong/setup-inso@v2
        with:
          inso-version: 2.4.0
      - name: Lint
        run: inso lint spec "Insomnia_2025-09-01.yaml" --ci
      - name: Run test suites
        run: inso run test "NYTTopStoriesTests" --env "Swagger env" --ci --src "Insomnia_2025-09-01.yank" --verbose --keepFile
