# .github/workflows/CICD.yml
name:
  Tests
on: 
  push:

jobs:
  Windows:
    name: Validate API spec
    runs-on: windows-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v1
      - uses: kong/setup-inso@v1
        with:
          inso-version: 3.5
      - name: Lint
        run: inso lint spec "Insomnia_2024-07-11.json" --ci
      - name: Run test suites
        run: inso run test "Article Search" --env Swagger env --ci
