# .github/workflows/CICD.yml
name:
  Tests
on: 
  push:

jobs:
  Windows:
    name: Validate API spec
    runs-on: windows-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v1
      - uses: kong/setup-inso@v2
        with:
          inso-version: 11.5.0
      - name: Lint           
        run: inso lint spec --workingDir "c:\Users\abost\AppData\Roaming\Insomnia\Insomnia_2025-09-02.yaml" --ci
      - name: Run test suites                                                           
        run: inso run test "NYTTopStoriesTests" -workingDir "c:\Users\abost\AppData\Roaming\Insomnia\Insomnia_2025-09-02.yaml" --env "Swagger env" --verbose
        
