# .github/workflows/CICD.yml
name:
  Test
on: 
  push:

jobs:
  Windows:
    name: Validate API spec
    runs-on: windows-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v1
      - uses: kong/setup-inso@v1
        with:
          inso-version: 9.3
      - name: Run test suites
        run: inso run test "NYT Lists Test By Date and Name" --keepFile --env "NYT_BOOKS_DEV" --verbose
