# .github/workflows/CICD.yml
name:
  Tests
on: 
  push:

jobs:
  Windows:
    name: Validate API spec
    runs-on: windows-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v1
      - uses: kong/setup-inso@v1
        with:
          inso-version: 2.4.0
      - name: Lint
        run: inso lint spec "Insomnia_2024-07-13.json" --ci
      - name: Run test suites
        run: inso run test "Article Search" --env "Swagger env" --ci --src "Insomnia_2024-07-13.json" --verbose --keepFile
      - name: Generate list using Markdown
        run: |
          echo "This is the lead in sentence for the list" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY # this is a blank line
          echo "- Lets add a bullet point" >> $GITHUB_STEP_SUMMARY
          echo "- Lets add a second bullet point" >> $GITHUB_STEP_SUMMARY
          echo "- How about a third one?" >> $GITHUB_STEP_SUMMARY
