# .github/workflows/CICD.yml
name:
  Tests
on: 
  push:

jobs:
  Windows:
    name: Validate API spec
    runs-on: windows-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v1
      - uses: kong/setup-inso@v1
        with:
          inso-version: 3.5
      - name: Run test suites
        working-directory: C:\Program Files\PowerShell\7
        run: Start-Process -FilePath "C:\INSO\cinso.bat" -Wait 
